# Generated by Django 4.1.3 on 2022-11-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
    ]
