# Generated by Django 4.1.3 on 2022-12-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_cliente_empleado_inventario_delete_familiares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='serie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
